ServerEvents.recipes(event => {
    registerVanillaRecipes(event)
    RegisterTFMGRecipes(event)
    RegistryCCTRecipes(event)
    RegistryTconstructResipes(event)
    RegistrySmelteryRecipes(event)
    RegisterAE2Recipes(event)
    RegistryTGCEURecipes(event)
    RegisterBotaniaRecipes(event)
    RegisterSophisBackpacksRecipes(event)
    RegisterCreateRecipes(event)
    RegisterTConSmelteryCompat(event)
})
ServerEvents.tags('item', event => {
    RegisterItemsTagsMain(event)
    RegisterCreateTags(event)
})
ServerEvents.tags('block', event =>{
    RegisterBotaniaTagsBlock(event)
})