ServerEvents.recipes(event => {
    registerVanillaRecipes(event)
    console.log('Registered Vanilla recipes')
    RegisterTFMGRecipes(event)
    console.log('Registered TFMG recipes')
    RegistryCCTRecipes(event)
    console.log('Registered DarkRealms recipes')
    RegistryTconstructResipes(event)
    console.log('Registered Tconstruct recipes')
    RegistrySmelteryRecipes(event)
    console.log('Registered TCSmeltery recipes')
    RegisterAE2Recipes(event)
    console.log('Registered AE2 recipes')
    RegistryTGCEURecipes(event)
    console.log('Registered GTCEU recipes')
    RegisterBotaniaRecipes(event)
    console.log('Registered Botania recipes')
    RegisterSophisBackpacksRecipes(event)
    console.log('Registered SBackpacks recipes')
    RegisterCreateRecipes(event)
    console.log('Registered Create recipes')
    RegisterTConSmelteryCompat(event)
    console.log('Registered TCSCompat recipes')
    RegisterApothRecipes(event)
    console.log('Registered Apotheosis recipes')
    RegisterCreateCompatRecipes(event)
    console.log('Registered Create compats')
    //build 0.2.27082025 21:55
    RegisterCBSRecipes(event)
    RegistryCreateGTMCrafterRecipes(event)
    RegistryBMRecipes(event)
    RegistrySeqAssembleGTPartsRecipes(event)
    RegisterApothCreateTicCompat(event)
    RegisterMalumRecipes(event)
    RegistryInfAbyssRecipes(event)
    //v0.1.10092025 6:48
    RegistryTCONTweaks(event)
})
ServerEvents.tags('item', event => {
    RegisterItemsTagsMain(event)
    RegisterCreateTags(event)
    RegisterMalumTags(event)
})
ServerEvents.tags('block', event =>{
    RegisterBotaniaTagsBlock(event)
})
GTCEuServerEvents.oreVeins(event => {
    //v0.1.13092025 22:20
    AdAstraMoon(event)
    AdAstraMars(event)
    AdAstraVenus(event)
    //v0.1.14092025 18:50
    AdAstraMercury(event)
    //v0.1.13092025 23:20
    InfAbyssFirstLayer(event)
    InfAbyssSecondLayer(event)
})