
/**
 * @type {string[]} MOD_IDS
 */
global.MOD_IDS = {
    IE: 'immersiveengineering',
    GT: 'gtceu',
    MC: 'minecraft',
    AE: 'ae2',
    FA: 'forbidden_arcanus',
    SB: 'sophisticatedbackpacks',
    SS: 'sophisticatedstorage',
    BT: 'botania',
    ML: 'malum',
    CT: 'create',
    AP: 'apotheosis',
    BO: 'biomesoplenty',
    BG: 'biomeswevegone',
    IA: 'infinite_abyss',
    IB: 'irons_spellbooks',
    TC: 'tconstruct',
    BM: 'bloodmagic',
    KJ: 'kubejs'
};
//discontined in kubejs delete after developed mod
/**
 * @type {Object} ORE_VARIANTS
 * @property {string} name - The name of the ore variant
 * @property {string} type - The type of the ore variant (e.g., 'metal', 'gem')
 * @property {number} tier - The tier level of the ore variant
 * @property {string} namespace - The namespace associated with the ore variant (e.g., mod ID)
 * @property {number} color - The color used for generate textures
 * @property {bool} pure - Whether the ore variant is pure or not
 */
global.ORE_VARIANTS = [
    {name: 'iron', type: 'metal', tier: 1, namespace: 'minecraft', color: 0xeeeeee, pure: true},
    {name: 'copper', type: 'metal', tier: 1, namespace: 'minecraft', color: 0xe77c56, pure: false},
    {name: 'gold', type: 'metal', tier: 2, namespace: 'minecraft', color: 0xfdf55f, pure: true},
    {name: 'diamond', type: 'gem', tier: 3, namespace: 'minecraft', color: 0xC8FFFF, pure: true},
    {name: 'nether_quartz', type: 'gem', tier: 1, namespace: 'minecraft', color: 0xf8efe3, pure: false},
    {name: 'magnesite', type: 'metal', tier: 1, namespace: 'gtceu', color: 0xfbfbf6, pure: false},
    {name: 'magnetite', type: 'metal', tier: 1, namespace: 'gtceu', color: 0x9d9d9d, pure: true},
    {name: 'malachite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x00f1b0, pure: true},
    {name: 'molybdenum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xc1c1ce, pure: true},
    {name: 'molybdenite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xe3ddc3, pure: true},
    {name: 'naquadah', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'neodymium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x6c5863, pure: true},
    {name: 'nickel', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xccdff5, pure: true},
    {name: 'tin', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xfafeff, pure: true},
    {name: 'aluminium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x7db9d8, pure: true},
    {name: 'beryllium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x73d73d, pure: true},
    {name: 'blazeium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'bornite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffe05a, pure: true},
    {name: 'vanadium_magnetite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x505d70, pure: true},
    {name: 'tungstate', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xe0ffc4, pure: true},
    {name: 'galena', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xf3e8fa, pure: true},
    {name: 'garnierite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x32c880, pure: true},
    {name: 'hematite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xff7161, pure: true},
    {name: 'bauxite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xcfb853, pure: true},
    {name: 'deorum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'desh', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'calorite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'cobalt', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x5050FA, pure: true},
    {name: 'wulfenite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xff9000, pure: true},
    {name: 'cassiterite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x89847e, pure: true},
    {name: 'cinnabar', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xff335f, pure: true},
    {name: 'goethite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'goldite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'ilmenite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'iridium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'cloggrum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'cobaltite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x1975ff, pure: true},
    {name: 'lepidolite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffdae4, pure: true},
    {name: 'cassiterite_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x89847e, pure: true},
    {name: 'lithium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd7e7ee, pure: true},
    {name: 'yellow_limonite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xf5e315, pure: true},
    {name: 'kyanite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd5ffff, pure: true},
    {name: 'scheelite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd7e8b3, pure: true},
    {name: 'cooperite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xe9ffa7, pure: true},
    {name: 'ebonite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'osmium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'nagrilite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'palladium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xbd92b5, pure: true},
    {name: 'pentlandite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xe3cf13, pure: true},
    {name: 'pyrite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xfffee6, pure: true},
    {name: 'pyrolusite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xc7b5ab, pure: true},
    {name: 'pyrochlore', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd5ffff, pure: true},
    {name: 'platinum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xfff4ba, pure: true},
    {name: 'plutonium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xba2727, pure: true},
    {name: 'powellite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd8cfac, pure: true},
    {name: 'pollucite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xeed9e1, pure: true},
    {name: 'relict', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'lead', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x7e6f82, pure: true},
    {name: 'silver', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xDCDCFF, pure: true},
    {name: 'spodumene', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffbcbc, pure: true},
    {name: 'stibnite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x656565, pure: true},
    {name: 'sphalerite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffdc88, pure: true},
    {name: 'tantalite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x4e6b94, pure: true},
    {name: 'tenebrum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'tetrahedrite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xa3a09b, pure: true},
    {name: 'thorium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x25411b, pure: true},
    {name: 'uraninite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffd52e, pure: true},
    {name: 'pitchblende', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffd647, pure: true},
    {name: 'chalcocite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x657882, pure: true},
    {name: 'chalcopyrite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x96c185, pure: true},
    {name: 'chromite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xc5c1a8, pure: true},
    {name: 'amethyst', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xcfa0f3, pure: true},
    {name: 'lazurite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x2836f1, pure: true},
    {name: 'graphite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xa8a89e, pure: true},
    {name: 'coal', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x393e41, pure: true},
    {name: 'apatite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x06cdf1, pure: true},
    {name: 'lapis', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x85a9ff, pure: true},
    {name: 'graphene', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'zeolite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf2e3e0, pure: true},
    {name: 'asbestos', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xE6E6E6, pure: true},
    {name: 'monazite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xd0ee98, pure: true},
    {name: 'granitic_mineral_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xd69077, pure: true},
    {name: 'electrotine', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x83cbf5, pure: true},
    {name: 'basaltic_mineral_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x5c5c5c, pure: true},
    {name: 'olivine', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xa7e404, pure: true},
    {name: 'garnet_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'blue_topaz', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xdbfeff, pure: true},
    {name: 'barite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'soapstone', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x5a7261, pure: true},
    {name: 'glauconite_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x1da351, pure: true},
    {name: 'mica', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xecfeff, pure: true},
    {name: 'bastnasite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xcaab60, pure: true},
    {name: 'fullers_earth', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf3efbb, pure: true},
    {name: 'bentonite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xede8a3, pure: true},
    {name: 'oilsands', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xe3c78a, pure: true},
    {name: 'alunite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfbd677, pure: true},
    {name: 'sulfur', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfdff31, pure: true},
    {name: 'virilux', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'certus_quartz', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xc2d6ff, pure: true},
    {name: 'almandine', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xa21717, pure: true},
    {name: 'saltpeter', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xE6E6E6, pure: true},
    {name: 'gypsum', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfffaec, pure: true},
    {name: 'emerald', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x17ff6c, pure: true},
    {name: 'spessartine', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffa81e, pure: true},
    {name: 'sapphire', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x3235e3, pure: true},
    {name: 'night_crystal', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'green_sapphire', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x9ae6b0, pure: true},
    {name: 'talc', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xebffe9, pure: true},
    {name: 'ruby', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xd72310, pure: true},
    {name: 'red_garnet', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x950c15, pure: true},
    {name: 'yellow_garnet', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf6ff09, pure: true},
    {name: 'dark_pearl', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'rendium', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'quartzite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf2f5ed, pure: true},
    {name: 'sulfur_dioxide', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'topaz', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xe8d73a, pure: true},
    {name: 'redstone', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xff0000, pure: true}, 
    {name: 'rock_salt', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffeae1, pure: true},
    {name: 'diatomite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfffafa, pure: true},
    {name: 'tricalcium_phosphate', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfffddb, pure: true},
    {name: 'realgar', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xff3d33, pure: true},
    {name: 'opal', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf9e3ea, pure: true},
    {name: 'calcite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfffef8, pure: true},
    {name: 'grossular', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffb777, pure: true},
    {name: 'trona', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff, pure: true},
    {name: 'pyrope', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xe81958, pure: true},
    {name: 'sodalite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x3d54ff, pure: true},
    {name: 'salt', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xFAFAFA, pure: true}
];
