
/**
 * @type {string[]} MOD_IDS
 */
global.MOD_IDS = {
    IE: 'immersiveengineering',
    GT: 'gtceu',
    MC: 'minecraft',
    AE: 'ae2',
    FA: 'forbidden_arcanus',
    SB: 'sophisticatedbackpacks',
    SS: 'sophisticatedstorage',
    BT: 'botania',
    ML: 'malum',
    CT: 'create',
    AP: 'apotheosis',
    BO: 'biomesoplenty',
    BG: 'biomeswevegone',
    IA: 'infinite_abyss',
    IB: 'irons_spellbooks',
    TC: 'tconstruct',
    BM: 'bloodmagic',
    KJ: 'kubejs'
};
/**
 * @type {Object} ORE_VARIANTS
 * @property {string} name - The name of the ore variant
 * @property {string} type - The type of the ore variant (e.g., 'metal', 'gem')
 * @property {number} tier - The tier level of the ore variant
 * @property {string} namespace - The namespace associated with the ore variant (e.g., mod ID)
 * @property {number} color - The color used for generate textures
 */
global.ORE_VARIANTS = [
    {name: 'iron', type: 'metal', tier: 1, namespace: 'minecraft', color: 0xD8D8D8},
    {name: 'copper', type: 'metal', tier: 1, namespace: 'minecraft', color: 0xFFA45C},
    {name: 'gold', type: 'metal', tier: 2, namespace: 'minecraft', color: 0xFFFF4D},
    {name: 'diamond', type: 'gem', tier: 3, namespace: 'minecraft', color: 0x4DFBFF},
    {name: 'emerald', type: 'gem', tier: 3, namespace: 'minecraft', color: 0x4DFF88},
    {name: 'nether_quartz', type: 'gem', tier: 1, namespace: 'minecraft', color: 0xE0E0E0},
    {name: 'magnesite', type: 'metal', tier: 1, namespace: 'gtceu', color: 0xa8a8a8},
    {name: 'magnetite', type: 'metal', tier: 1, namespace: 'gtceu', color: 0x039382},
    {name: 'malachite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x4dff88},
    {name: 'molybdenum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x8c8c8c},
    {name: 'molybdenite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'naquadah', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'neodymium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'nickel', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'tin', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'aluminium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'beryllium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'blazeium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'bornite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'vanadium_magnetite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'tungstate', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'galena', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'garnierite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'hematite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'bauxite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'deorum', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'desh', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'calorite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'cobalt', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'wulfenite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'cassiterite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'cinnabar', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'goethite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'goldite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'ilmenite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'iridium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'cloggrum', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'cobaltite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'lepidolite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'cassiterite_sand', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'lithium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'yellow_limonite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'kyanite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'scheelite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'cooperite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'ebonite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'electrum', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'osmium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'nagrilite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'palladium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'pentlandite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'pyrite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'pyrolusite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'pyrochlore', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'platinum', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'plutonium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'powellite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'pollucite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'relict', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'lead', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'silver', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'spodumene', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'stibnite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'sphalerite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'tantalite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'tenebrum', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'tetrahedrite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'thorium', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'uraninite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'pitchblende', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'chalcocite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'chalcopyrite', type: 'metal', tier: 2, namespace: 'gtceu'},
    {name: 'chromite', type: 'metal', tier: 2, namespace: 'gtceu'}
];