
/**
 * @type {string[]} MOD_IDS
 */
global.MOD_IDS = {
    IE: 'immersiveengineering',
    GT: 'gtceu',
    MC: 'minecraft',
    AE: 'ae2',
    FA: 'forbidden_arcanus',
    SB: 'sophisticatedbackpacks',
    SS: 'sophisticatedstorage',
    BT: 'botania',
    ML: 'malum',
    CT: 'create',
    AP: 'apotheosis',
    BO: 'biomesoplenty',
    BG: 'biomeswevegone',
    IA: 'infinite_abyss',
    IB: 'irons_spellbooks',
    TC: 'tconstruct',
    BM: 'bloodmagic',
    KJ: 'kubejs'
};
/**
 * @type {Object} ORE_VARIANTS
 * @property {string} name - The name of the ore variant
 * @property {string} type - The type of the ore variant (e.g., 'metal', 'gem')
 * @property {number} tier - The tier level of the ore variant
 * @property {string} namespace - The namespace associated with the ore variant (e.g., mod ID)
 * @property {number} color - The color used for generate textures
 */
global.ORE_VARIANTS = [
    {name: 'iron', type: 'metal', tier: 1, namespace: 'minecraft', color: 0xeeeeee},
    {name: 'copper', type: 'metal', tier: 1, namespace: 'minecraft', color: 0xe77c56},
    {name: 'gold', type: 'metal', tier: 2, namespace: 'minecraft', color: 0xfdf55f},
    {name: 'diamond', type: 'gem', tier: 3, namespace: 'minecraft', color: 0xC8FFFF},
    {name: 'nether_quartz', type: 'gem', tier: 1, namespace: 'minecraft', color: 0xf8efe3},
    {name: 'magnesite', type: 'metal', tier: 1, namespace: 'gtceu', color: 0xfbfbf6},
    {name: 'magnetite', type: 'metal', tier: 1, namespace: 'gtceu', color: 0x9d9d9d},
    {name: 'malachite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x00f1b0},
    {name: 'molybdenum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xc1c1ce},
    {name: 'molybdenite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xe3ddc3},
    {name: 'naquadah', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'neodymium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x6c5863},
    {name: 'nickel', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xccdff5},
    {name: 'tin', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xfafeff},
    {name: 'aluminium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x7db9d8},
    {name: 'beryllium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x73d73d},
    {name: 'blazeium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'bornite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffe05a},
    {name: 'vanadium_magnetite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x505d70},
    {name: 'tungstate', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xe0ffc4},
    {name: 'galena', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xf3e8fa},
    {name: 'garnierite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x32c880},
    {name: 'hematite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xff7161},
    {name: 'bauxite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xcfb853},
    {name: 'deorum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'desh', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'calorite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'cobalt', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x5050FA},
    {name: 'wulfenite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xff9000},
    {name: 'cassiterite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x89847e},
    {name: 'cinnabar', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xff335f},
    {name: 'goethite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'goldite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'ilmenite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'iridium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'cloggrum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'cobaltite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x1975ff},
    {name: 'lepidolite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffdae4},
    {name: 'cassiterite_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x89847e},
    {name: 'lithium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd7e7ee},
    {name: 'yellow_limonite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xf5e315},
    {name: 'kyanite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd5ffff},
    {name: 'scheelite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd7e8b3},
    {name: 'cooperite', type: 'metal', tier: 2, namespace: 'gtceu', colro: 0xe9ffa7},
    {name: 'ebonite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'osmium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'nagrilite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'palladium', type: 'metal', tier: 2, namespace: 'gtceu',color: 0xbd92b5},
    {name: 'pentlandite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xe3cf13},
    {name: 'pyrite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xfffee6},
    {name: 'pyrolusite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xc7b5ab},
    {name: 'pyrochlore', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd5ffff},
    {name: 'platinum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xfff4ba},
    {name: 'plutonium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xba2727},
    {name: 'powellite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xd8cfac},
    {name: 'pollucite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xeed9e1},
    {name: 'relict', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'lead', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x7e6f82},
    {name: 'silver', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xDCDCFF},
    {name: 'spodumene', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffbcbc},
    {name: 'stibnite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x656565},
    {name: 'sphalerite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffdc88},
    {name: 'tantalite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x4e6b94},
    {name: 'tenebrum', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'tetrahedrite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xa3a09b},
    {name: 'thorium', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x25411b},
    {name: 'uraninite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffd52e},
    {name: 'pitchblende', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xffd647},
    {name: 'chalcocite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x657882},
    {name: 'chalcopyrite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0x96c185},
    {name: 'chromite', type: 'metal', tier: 2, namespace: 'gtceu', color: 0xc5c1a8},
    {name: 'amethyst', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xcfa0f3},
    {name: 'lazurite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x2836f1},
    {name: 'graphite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xa8a89e},
    {name: 'coal', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x393e41},
    {name: 'apatite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x06cdf1},
    {name: 'lapis', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x85a9ff},
    {name: 'graphene', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'zeolite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf2e3e0},
    {name: 'asbestos', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xE6E6E6},
    {name: 'monazite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xd0ee98},
    {name: 'granitic_mineral_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xd69077},
    {name: 'electrotine', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x83cbf5},
    {name: 'basaltic_mineral_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x5c5c5c},
    {name: 'olivine', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xa7e404},
    {name: 'garnet_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'blue_topaz', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xdbfeff},
    {name: 'barite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'soapstone', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x5a7261},
    {name: 'glauconite_sand', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x1da351},
    {name: 'mica', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xecfeff},
    {name: 'bastnasite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xcaab60},
    {name: 'fullers_earth', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf3efbb},
    {name: 'bentonite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xede8a3},
    {name: 'oilsands', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xe3c78a},
    {name: 'alunite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfbd677},
    {name: 'sulfur', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfdff31},
    {name: 'virilux', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'certus_quartz', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xc2d6ff},
    {name: 'almandine', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xa21717},
    {name: 'saltpeter', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xE6E6E6},
    {name: 'gypsum', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfffaec},
    {name: 'emerald', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x17ff6c},
    {name: 'spessartine', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffa81e},
    {name: 'sapphire', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x3235e3},
    {name: 'night_crystal', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'green_sapphire', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x9ae6b0},
    {name: 'talc', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xebffe9},
    {name: 'ruby', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xd72310},
    {name: 'red_garnet', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x950c15},
    {name: 'yellow_garnet', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf6ff09},
    {name: 'dark_pearl', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'rendium', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'quartzite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf2f5ed},
    {name: 'sulfur_dioxide', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'topaz', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xe8d73a},
    {name: 'redstone', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xff0000}, 
    {name: 'rock_salt', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffeae1},
    {name: 'diatomite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfffafa},
    {name: 'tricalcium_phosphate', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfffddb},
    {name: 'realgar', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xff3d33},
    {name: 'opal', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xf9e3ea},
    {name: 'calcite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xfffef8},
    {name: 'grossular', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffb777},
    {name: 'trona', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xffffff},
    {name: 'pyrope', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xe81958},
    {name: 'sodalite', type: 'gem', tier: 2, namespace: 'gtceu', color: 0x3d54ff},
    {name: 'salt', type: 'gem', tier: 2, namespace: 'gtceu', color: 0xFAFAFA}
];
