#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jan 13 00:47:31 YEKT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=AtmosphericShaders_0.0.4.zip
enableShaders=false
