#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Dec 25 12:22:55 YEKT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryReimagined_r5.6.1 + EuphoriaPatches_1.7.2
enableShaders=false
