#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Dec 27 21:54:54 YEKT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryReimagined_r5.6.1 + EuphoriaPatches_1.7.2
enableShaders=false
