const RegisterGTTagsBlocks = (event) => {
  var oreList = [
    "#forge:ores_in_ground/deepstone",
    "#forge:ores_in_ground/depthrock",
    "#forge:ores_in_ground/red_deepstone",
    "#forge:ores_in_ground/moon_stone",
    "#forge:ores_in_ground/phyllite",
    "#forge:ores_in_ground/slate",
    "#forge:ores_in_ground/gabbro",
    "#forge:ores_in_ground/gabbro_regolith",
    "#forge:ores_in_ground/granodiorite",
    "#forge:ores_in_ground/granodiorite_regolith",
    "#forge:ores_in_ground/rhyolite",
    "#forge:ores_in_ground/beige_limestone",
    "#forge:ores_in_ground/siltstone",
    "#forge:ores_in_ground/conglomerate",
    "#forge:ores_in_ground/grey_limestone",
    "#forge:ores_in_ground/mudstone",
    "#forge:ores_in_ground/quartzite",
    "#forge:ores_in_ground/dolerite",
    "#forge:ores_in_ground/daciteun",
    "#forge:ores_in_ground/white_granite",
    "#forge:ores_in_ground/limestone",
    "#forge:ores_in_ground/pillow_basalt",
    "#forge:ores_in_ground/dacite",
    "#forge:ores_in_ground/mars_stone",
    "#forge:ores_in_ground/venus_stone",
    "#forge:ores_in_ground/mercury_stone",
    "#forge:ores_in_ground/root",
    "#forge:ores_in_ground/nightstone",
    "#forge:ores_in_ground/deepstone",
  ];
  event.add("minecraft:mineable/pickaxe", oreList);
};
